# Pipeline to run basic code quality tests as part of pull requests to the master branch.

trigger: none
pr:
  branches:
    include:
      # Until Flux V2 integration is in Public Preview, work with FluxV2 branch.
      # Once Flux V2 integration is in Public Preview, FluxV2 branch will be merged into the default branch.
        - FluxV2

variables:
  - group: az-vote-app-dev

pool:
  vmImage: "ubuntu-latest"

steps:
  - template: code-quality-template.yaml
